In [1]:
import pandas as pd

In [52]:
data = pd.read_csv('loan_check.csv')

In [53]:
data.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [55]:
data.drop(columns = ['loan_id'], inplace = True)

In [6]:
data.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [56]:
data.columns= data.columns.str.strip()  # remove extra space in columns

In [57]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [58]:
data['assets'] = data.residential_assets_value+data.commercial_assets_value+data.luxury_assets_value+data.bank_asset_value

In [ ]:
# all types of assets columns combine as assets

In [59]:
# drop self_employed column and all types of assets columns as we have combined them as assets column
data.drop(columns=['residential_assets_value','bank_asset_value','commercial_assets_value','luxury_assets_value','self_employed'],axis = 1,inplace=True)

In [60]:
data.head()

,no_of_dependents,education,income_annum,loan_amount,loan_term,cibil_score,loan_status,assets
0,2,Graduate,9600000,29900000,12,778,Approved,50700000
1,0,Not Graduate,4100000,12200000,8,417,Rejected,17000000
2,3,Graduate,9100000,29700000,20,506,Rejected,57700000
3,3,Graduate,8200000,30700000,8,467,Rejected,52700000
4,5,Not Graduate,9800000,24200000,20,382,Rejected,55000000

In [61]:
data.isnull().sum()

no_of_dependents    0
education           0
income_annum        0
loan_amount         0
loan_term           0
cibil_score         0
loan_status         0
assets              0
dtype: int64

In [62]:
data.education.unique()  # categorical values name

array([' Graduate', ' Not Graduate'], dtype=object)

In [63]:
def clean_data(st):
    st = st.strip()
    return st

In [64]:
clean_data(' Graduate')

'Graduate'

In [65]:
data.education = data.education.apply(clean_data)

In [66]:
data.education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [67]:
data['education'] = data['education'].replace(['Graduate', 'Not Graduate'],[1,0])

C:\Users\suman\AppData\Local\Temp\ipykernel_25468\94172871.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['education'] = data['education'].replace(['Graduate', 'Not Graduate'],[1,0])

In [68]:
data.head()

,no_of_dependents,education,income_annum,loan_amount,loan_term,cibil_score,loan_status,assets
0,2,1,9600000,29900000,12,778,Approved,50700000
1,0,0,4100000,12200000,8,417,Rejected,17000000
2,3,1,9100000,29700000,20,506,Rejected,57700000
3,3,1,8200000,30700000,8,467,Rejected,52700000
4,5,0,9800000,24200000,20,382,Rejected,55000000

In [69]:
data.loan_status.unique()

array([' Approved', ' Rejected'], dtype=object)

In [70]:
data.loan_status = data.loan_status.apply(clean_data)

In [71]:
data.loan_status = data.loan_status.replace(['Approved', 'Rejected'],[1,0])

C:\Users\suman\AppData\Local\Temp\ipykernel_25468\697167504.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.loan_status = data.loan_status.replace(['Approved', 'Rejected'],[1,0])

In [72]:
data.head()   # completete data as clean

,no_of_dependents,education,income_annum,loan_amount,loan_term,cibil_score,loan_status,assets
0,2,1,9600000,29900000,12,778,1,50700000
1,0,0,4100000,12200000,8,417,0,17000000
2,3,1,9100000,29700000,20,506,0,57700000
3,3,1,8200000,30700000,8,467,0,52700000
4,5,0,9800000,24200000,20,382,0,55000000

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
input_data = data.drop(columns=['loan_status'])
output_data = data['loan_status']

In [75]:
output_data

0       1
1       0
2       0
3       0
4       0
       ..
4264    0
4265    1
4266    0
4267    1
4268    1
Name: loan_status, Length: 4269, dtype: int64

In [32]:
input_data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,assets
0,2,1,No,9600000,29900000,12,778,50700000
1,0,0,Yes,4100000,12200000,8,417,17000000
2,3,1,No,9100000,29700000,20,506,57700000
3,3,1,No,8200000,30700000,8,467,52700000
4,5,0,Yes,9800000,24200000,20,382,55000000
...,...,...,...,...,...,...,...,...
4264,5,1,Yes,1000000,2300000,12,317,7400000
4265,0,0,Yes,3300000,11300000,20,559,20000000
4266,2,0,No,6500000,23900000,18,457,39000000
4267,1,0,No,4100000,12800000,8,780,28800000
4268,1,1,No,9200000,29700000,10,607,77300000

In [82]:
x_train,x_test,y_train,y_test = train_test_split(input_data,output_data,test_size=0.2,random_state=42) # splitting

In [83]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3415, 7), (854, 7), (3415,), (854,))

In [84]:
from sklearn.preprocessing import StandardScaler  # for improving the performances of model

In [85]:
scaler = StandardScaler()

In [86]:
x_train_scaled = scaler.fit_transform(x_train)

In [87]:
x_test_scaled = scaler.transform(x_test)

In [88]:
from sklearn.linear_model import LogisticRegression

In [89]:
model = LogisticRegression()

In [90]:
model.fit(x_train_scaled,y_train)

LogisticRegression()

In [91]:
model.score(x_test_scaled,y_test)

0.9098360655737705

In [94]:
pred_data = pd.DataFrame([['2',	'1',	'9600000',	'29900000',	'12',	'778',	'50700000']],columns = ['no_of_dependents',	'education',	'income_annum',	'loan_amount',	'loan_term',	'cibil_score',	'assets'])

In [95]:
pred_data =scaler.transform(pred_data)

In [96]:
model.predict(pred_data)

array([1])

In [ ]:
# '1' shows means approved

In [97]:
import pickle as pk

In [102]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [104]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(x_train_scaled,y_train)

RandomForestClassifier(random_state=42)

In [105]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [106]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

In [108]:
# logistic regression model evaluation
y_pred_lr = model.predict(x_test_scaled)
print("Logistic Regression Metrics:")
print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall   :", recall_score(y_test, y_pred_lr))
print("F1 Score :", f1_score(y_test, y_pred_lr))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_lr))

Logistic Regression Metrics:
Accuracy : 0.9098360655737705
Precision: 0.9242144177449169
Recall   : 0.9328358208955224
F1 Score : 0.9285051067780873
ROC AUC  : 0.9019525016427299

In [109]:
# decision tree model evaluation
y_pred_dt = dt_model.predict(x_test_scaled)
print("Decision Tree Metrics:")
print("Accuracy :", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall   :", recall_score(y_test, y_pred_dt))
print("F1 Score :", f1_score(y_test, y_pred_dt))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_dt))

Decision Tree Metrics:
Accuracy : 0.9859484777517564
Precision: 0.9869888475836431
Recall   : 0.9906716417910447
F1 Score : 0.9888268156424581
ROC AUC  : 0.9843295315873463

In [110]:
# Random Forest model evaluation
y_pred_rf = rf_model.predict(x_test_scaled)
print("Random Forest Metrics:")
print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall   :", recall_score(y_test, y_pred_rf))
print("F1 Score :", f1_score(y_test, y_pred_rf))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_rf))

Random Forest Metrics:
Accuracy : 0.9800936768149883
Precision: 0.9779005524861878
Recall   : 0.9906716417910447
F1 Score : 0.9842446709916589
ROC AUC  : 0.9764678963672204

In [111]:
# knn model evaluation
y_pred_knn = knn_model.predict(x_test_scaled)
print("KNN Metrics:")
print("Accuracy :", accuracy_score(y_test, y_pred_knn))
print("Precision:", precision_score(y_test, y_pred_knn))
print("Recall   :", recall_score(y_test, y_pred_knn))
print("F1 Score :", f1_score(y_test, y_pred_knn))
print("ROC AUC  :", roc_auc_score(y_test, y_pred_knn))

KNN Metrics:
Accuracy : 0.9285714285714286
Precision: 0.9489603024574669
Recall   : 0.9365671641791045
F1 Score : 0.9427230046948357
ROC AUC  : 0.925830751900873

In [112]:
with open('dt_model.pkl', 'wb') as f:
    pk.dump(dt_model, f)