Natural Language Processing (NLP) is a branch of Artificial Intelligence that helps computers understand, process, and analyze human language.

NLP is used in many real-world applications such as chatbots, language translation, spam detection, sentiment analysis, voice assistants, and text classification.

In this notebook, we will learn basic NLP preprocessing techniques such as Tokenization, Stopword Removal, Stemming, Lemmatization, TF-IDF, and Sentiment Analysis.

In [1]:
# Import Libraries

import pandas as pd
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
# Download NLTK Resources

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\suman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\suman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\suman\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\suman\AppData\Roaming\nltk_data...

True

In [5]:
print(nltk.__version__)

3.9.1

In [6]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\suman\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\suman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

## Sample Sentences

The following five movie review sentences will be used to demonstrate different NLP preprocessing techniques.

In [3]:
sentences = [
    "The movie was absolutely amazing and enjoyable.",
    "I did not like the acting in the movie.",
    "The story was boring but the music was good.",
    "This is one of the best films I have ever watched.",
    "The movie was too long and disappointing."
]

for i, sentence in enumerate(sentences, start=1):
    print(f"Sentence {i}: {sentence}")

Sentence 1: The movie was absolutely amazing and enjoyable.
Sentence 2: I did not like the acting in the movie.
Sentence 3: The story was boring but the music was good.
Sentence 4: This is one of the best films I have ever watched.
Sentence 5: The movie was too long and disappointing.

# Tokenization

Tokenization is the process of breaking a sentence into individual words called tokens.

It is the first step in Natural Language Processing.

In [7]:
for i, sentence in enumerate(sentences, start=1):

    tokens = word_tokenize(sentence)

    print(f"\nSentence {i}")
    print("Original :", sentence)
    print("Tokens   :", tokens)

Sentence 1
Original : The movie was absolutely amazing and enjoyable.
Tokens   : ['The', 'movie', 'was', 'absolutely', 'amazing', 'and', 'enjoyable', '.']

Sentence 2
Original : I did not like the acting in the movie.
Tokens   : ['I', 'did', 'not', 'like', 'the', 'acting', 'in', 'the', 'movie', '.']

Sentence 3
Original : The story was boring but the music was good.
Tokens   : ['The', 'story', 'was', 'boring', 'but', 'the', 'music', 'was', 'good', '.']

Sentence 4
Original : This is one of the best films I have ever watched.
Tokens   : ['This', 'is', 'one', 'of', 'the', 'best', 'films', 'I', 'have', 'ever', 'watched', '.']

Sentence 5
Original : The movie was too long and disappointing.
Tokens   : ['The', 'movie', 'was', 'too', 'long', 'and', 'disappointing', '.']

### Observation

Tokenization divides a sentence into individual words, making it easier for computers to understand and process text.

# Stopword Removal

Stopwords are common English words such as "the", "is", "was", "and", "in".

Removing stopwords helps reduce unnecessary words and improves text processing.

In [8]:
stop_words = set(stopwords.words("english"))

for i, sentence in enumerate(sentences, start=1):

    tokens = word_tokenize(sentence)

    filtered = []

    for word in tokens:
        if word.lower() not in stop_words:
            filtered.append(word)

    print(f"\nSentence {i}")
    print("Original :", sentence)
    print("Filtered :", filtered)

Sentence 1
Original : The movie was absolutely amazing and enjoyable.
Filtered : ['movie', 'absolutely', 'amazing', 'enjoyable', '.']

Sentence 2
Original : I did not like the acting in the movie.
Filtered : ['like', 'acting', 'movie', '.']

Sentence 3
Original : The story was boring but the music was good.
Filtered : ['story', 'boring', 'music', 'good', '.']

Sentence 4
Original : This is one of the best films I have ever watched.
Filtered : ['one', 'best', 'films', 'ever', 'watched', '.']

Sentence 5
Original : The movie was too long and disappointing.
Filtered : ['movie', 'long', 'disappointing', '.']

### Observation

Stopword Removal removes common words that usually do not add much meaning to a sentence.

# Stemming

Stemming reduces words to their root form by removing prefixes or suffixes.

The resulting word may not always be a proper English word.

In [9]:
stemmer = PorterStemmer()

for i, sentence in enumerate(sentences, start=1):

    tokens = word_tokenize(sentence)

    stemmed = []

    for word in tokens:
        if word.isalpha():
            stemmed.append(stemmer.stem(word))

    print(f"\nSentence {i}")
    print("Original :", sentence)
    print("Stemmed  :", stemmed)

Sentence 1
Original : The movie was absolutely amazing and enjoyable.
Stemmed  : ['the', 'movi', 'wa', 'absolut', 'amaz', 'and', 'enjoy']

Sentence 2
Original : I did not like the acting in the movie.
Stemmed  : ['i', 'did', 'not', 'like', 'the', 'act', 'in', 'the', 'movi']

Sentence 3
Original : The story was boring but the music was good.
Stemmed  : ['the', 'stori', 'wa', 'bore', 'but', 'the', 'music', 'wa', 'good']

Sentence 4
Original : This is one of the best films I have ever watched.
Stemmed  : ['thi', 'is', 'one', 'of', 'the', 'best', 'film', 'i', 'have', 'ever', 'watch']

Sentence 5
Original : The movie was too long and disappointing.
Stemmed  : ['the', 'movi', 'wa', 'too', 'long', 'and', 'disappoint']

### Observation

Stemming converts words into their root form.

Example:

playing → play

enjoyable → enjoy

amazing → amaz

# Lemmatization

Lemmatization converts words into meaningful dictionary words.

It produces better results than stemming.

In [10]:
lemmatizer = WordNetLemmatizer()

for i, sentence in enumerate(sentences, start=1):

    tokens = word_tokenize(sentence)

    lemmas = []

    for word in tokens:
        if word.isalpha():
            lemmas.append(lemmatizer.lemmatize(word))

    print(f"\nSentence {i}")
    print("Original      :", sentence)
    print("Lemmatization :", lemmas)

Sentence 1
Original      : The movie was absolutely amazing and enjoyable.
Lemmatization : ['The', 'movie', 'wa', 'absolutely', 'amazing', 'and', 'enjoyable']

Sentence 2
Original      : I did not like the acting in the movie.
Lemmatization : ['I', 'did', 'not', 'like', 'the', 'acting', 'in', 'the', 'movie']

Sentence 3
Original      : The story was boring but the music was good.
Lemmatization : ['The', 'story', 'wa', 'boring', 'but', 'the', 'music', 'wa', 'good']

Sentence 4
Original      : This is one of the best films I have ever watched.
Lemmatization : ['This', 'is', 'one', 'of', 'the', 'best', 'film', 'I', 'have', 'ever', 'watched']

Sentence 5
Original      : The movie was too long and disappointing.
Lemmatization : ['The', 'movie', 'wa', 'too', 'long', 'and', 'disappointing']

### Observation

Lemmatization converts words into meaningful base forms.

It is more accurate than stemming because the output is usually a valid English word.

# TF-IDF

TF-IDF (Term Frequency - Inverse Document Frequency) converts text into numerical values.

Machine Learning algorithms cannot understand text directly.

TF-IDF assigns higher importance to meaningful words and lower importance to common words.

In [11]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(sentences)

feature_names = vectorizer.get_feature_names_out()

tfidf = pd.DataFrame(
    X.toarray(),
    columns=feature_names
)

tfidf

,absolutely,acting,amazing,and,best,boring,but,did,disappointing,enjoyable,...,music,not,of,one,story,the,this,too,was,watched
0,0.457629,0.000000,0.457629,0.369212,0.000000,0.000000,0.000000,0.000000,0.000000,0.457629,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.218063,0.000000,0.000000,0.306479,0.000000
1,0.000000,0.396627,0.000000,0.000000,0.000000,0.000000,0.000000,0.396627,0.000000,0.000000,...,0.000000,0.396627,0.000000,0.000000,0.000000,0.377990,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.360322,0.360322,0.000000,0.000000,0.000000,...,0.360322,0.000000,0.000000,0.000000,0.360322,0.343390,0.000000,0.000000,0.482623,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.329206,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.329206,0.329206,0.000000,0.156869,0.329206,0.000000,0.000000,0.329206
4,0.000000,0.000000,0.000000,0.369212,0.000000,0.000000,0.000000,0.000000,0.457629,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.218063,0.000000,0.457629,0.306479,0.000000

### Observation

TF-IDF converts text into numbers.

These numerical values are used by Machine Learning algorithms for text classification.

# Sentiment Analysis

Sentiment Analysis is the process of identifying whether a piece of text expresses a Positive, Negative, or Neutral opinion.

Example:

"I loved this movie." → Positive

"The movie was boring." → Negative

In [12]:
reviews = [
    "Movie was amazing",
    "Excellent acting",
    "Worst movie ever",
    "I loved this movie",
    "Waste of time"
]

sentiments = [
    "Positive",
    "Positive",
    "Negative",
    "Positive",
    "Negative"
]

df = pd.DataFrame({
    "Review": reviews,
    "Sentiment": sentiments
})

df

               Review Sentiment
0   Movie was amazing  Positive
1    Excellent acting  Positive
2    Worst movie ever  Negative
3  I loved this movie  Positive
4       Waste of time  Negative

## Conclusion

In this notebook, we learned the basic NLP preprocessing techniques:

- Tokenization
- Stopword Removal
- Stemming
- Lemmatization
- TF-IDF
- Sentiment Analysis

These preprocessing techniques are important for cleaning text data before building Machine Learning and Deep Learning models.